### ISSUE TITLE
Mobile app show Sign In screen

### ISSUE THREAD

**Issue by saurabhperiwal** [nnmer/powerbi-embedded-react-native-demo#2]
{
    "accessToken": "***************",
    "embedUrl": "https://app.powerbi.com/reportEmbed?reportId=72a10e3c-2dda-44d0-b976-5e5eb7c9f8a3&autoAuth=true&ctid=2c887226-b7b5-4e97-9238-c9cdc3780f40&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLXdlc3QtdXMtcmVkaXJlY3QuYW5hbHlzaXMud2luZG93cy5uZXQvIn0%3D",
    "reportId": "72a10e3c-2dda-44d0-b976-5e5eb7c9f8a3"
}

This is after generating token using tokenGen, I am using my PowerBi and Azure login and I've not created new AD account.

**Comment by nnmer** [comment]
It seems that something is not correct with the permission setup.
This demo is based on a AD master account (the account with Global administrator permission). Whether your user has this permission set?

**Comment by nnmer** [comment]
The issue is in:
```
&autoAuth=true&ctid=2c887226-b7b5-4e97-9238-c9cdc3780f40
```

remove this from the embedUrl and it should work (as long as your user permissions are correct)
